name: main pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.10.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0
          cache: 'yarn'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --immutable  --immutable-cache 
      - run: yarn code:format

  lint-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.10.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0
          cache: 'yarn'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --immutable  --immutable-cache 
      - run: yarn code:lint

  typechecked-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.10.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0
          cache: 'yarn'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --immutable  --immutable-cache 
      - run: yarn code:typing

  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.10.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0
          cache: 'yarn'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --immutable  --immutable-cache 
      - run: yarn test:unit

  mutation-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.10.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0
          cache: 'yarn'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --immutable  --immutable-cache 
      - run: yarn test:mutation
